# Generated by Django 5.0.1 on 2024-02-21 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
